# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='Currency',
            field=models.CharField(max_length=23),
        ),
    ]
