# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_expense', '0003_delete_addexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expensetitle', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Currency', models.CharField(max_length=23)),
                ('PaymentType', models.CharField(max_length=30)),
                ('ExpenseType', models.CharField(max_length=200)),
                ('VendorName', models.CharField(max_length=200)),
            ],
        ),
    ]
