# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0004_addexpense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addexpense',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='addexpense',
            old_name='Currency',
            new_name='currency',
        ),
        migrations.RenameField(
            model_name='addexpense',
            old_name='Expensetitle',
            new_name='expensetitle',
        ),
        migrations.RenameField(
            model_name='addexpense',
            old_name='ExpenseType',
            new_name='expensetype',
        ),
        migrations.RenameField(
            model_name='addexpense',
            old_name='PaymentType',
            new_name='paymenttype',
        ),
        migrations.RenameField(
            model_name='addexpense',
            old_name='VendorName',
            new_name='vendorname',
        ),
    ]
