# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0004_addexpense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpense',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='Currency',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='ExpenseType',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='Expensetitle',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='PaymentType',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='VendorName',
        ),
        migrations.AddField(
            model_name='addexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addexpense',
            name='currency',
            field=models.CharField(default='', max_length=23, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addexpense',
            name='expense_title',
            field=models.CharField(default='', max_length=20, verbose_name='Expense Title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addexpense',
            name='expense_type',
            field=models.CharField(default='', max_length=200, verbose_name='Expense Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addexpense',
            name='payment_type',
            field=models.CharField(default='', max_length=30, verbose_name='Payment Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addexpense',
            name='vendor_name',
            field=models.CharField(default='', max_length=200, verbose_name='Vendor Name'),
            preserve_default=False,
        ),
    ]
