# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0006_auto_20180514_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='cc_ac_no',
            field=models.BigIntegerField(verbose_name='Cr_ac_no'),
        ),
    ]
