# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0007_auto_20180514_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='cc_ac_no',
            field=models.BigIntegerField(blank=True, verbose_name='Cr_ac_no'),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='expense_type',
            field=models.CharField(blank=True, max_length=200, verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='expensetype',
            field=models.CharField(blank=True, max_length=144, verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='invoice_id',
            field=models.CharField(blank=True, max_length=23, verbose_name='invoice id'),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Vendor Name'),
        ),
        migrations.AlterField(
            model_name='expense_on',
            name='type',
            field=models.CharField(blank=True, max_length=67),
        ),
        migrations.AlterField(
            model_name='payment_options',
            name='payment',
            field=models.CharField(blank=True, max_length=23),
        ),
    ]
