# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_expense', '0008_auto_20180514_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense_on',
        ),
        migrations.DeleteModel(
            name='Payment_options',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='cc_ac_no',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='expensetype',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='invoice_id',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='order_placed',
        ),
    ]
